### ISSUE TITLE
metalogo fails when --task_name or --output_name contains a period

### ISSUE THREAD

**Issue by acvill** [labomics/MetaLogo#1]
Thanks for making MetaLogo! I'm using v1.1.3.

## Works fine

```
name=sample_A

metalogo \
    --seq_file sampleA.fasta \
    --seq_file_type fasta \
    --sequence_type dna \
    --task_name ${name} \
    --output_name ${name} \
    --clustalo_bin /programs/clustalo \
    --fasttree_bin /programs/fasttree/FastTree \
    --fasttreemp_bin /programs/fasttree/FastTreeMP
```

## Fails

```
name=sample.A

metalogo \
    --seq_file sampleA.fasta \
    --seq_file_type fasta \
    --sequence_type dna \
    --task_name ${name} \
    --output_name ${name} \
    --clustalo_bin /programs/clustalo \
    --fasttree_bin /programs/fasttree/FastTree \
    --fasttreemp_bin /programs/fasttree/FastTreeMP
```

## Error message

```
Traceback (most recent call last):
  File "/home/miniconda3/envs/metalogo/bin/metalogo", line 8, in <module>
    sys.exit(main())
  File "/home/miniconda3/envs/metalogo/lib/python3.7/site-packages/MetaLogo/entry.py", line 310, in main
    run_from_args(args)
  File "/home/miniconda3/envs/metalogo/lib/python3.7/site-packages/MetaLogo/entry.py", line 62, in run_from_args
    logogroup.savefig(f'{args.output_dir}/{args.output_name}')
  File "/home/miniconda3/envs/metalogo/lib/python3.7/site-packages/MetaLogo/item.py", line 28, in savefig
    self.ax.get_figure().savefig(filename,bbox_inches=bbox_inches)
  File "/home/miniconda3/envs/metalogo/lib/python3.7/site-packages/matplotlib/figure.py", line 3058, in savefig
    self.canvas.print_figure(fname, **kwargs)
  File "/home/miniconda3/envs/metalogo/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2259, in print_figure
    canvas = self._get_output_canvas(backend, format)
  File "/home/miniconda3/envs/metalogo/lib/python3.7/site-packages/matplotlib/backend_bases.py", line 2190, in _get_output_canvas
    .format(fmt, ", ".join(sorted(self.get_supported_filetypes()))))
ValueError: Format 'a' is not supported (supported formats: eps, jpeg, jpg, pdf, pgf, png, ps, raw, rgba, svg, svgz, tif, tiff)
```

**Comment by yaowenacademic** [comment]
Hi acvill,
Sorry for the late response. I have fixed the bug. Please check the latest code.
